### PR TITLE
v0.0.1

### PR DESCRIPTION
**Pull request by SilkyFowl**

### CODE REVIEW

**Comment by SilkyFowl** [comment]
WHAT!?

image


dotnet/fsharp#8854
> Unfortunately I think only @dsyme has familiarity with this, since the expression API is not a part of the compiler proper. Perhaps @ncave and @alfonsogarciacaro can weigh in here since Fable uses this API extensively.
> 
> We'd certainly welcome a pull request here and we're happy to review it. But I'm not sure this will be a high priority for us to implement right now since no supported F# editor tooling makes use of this.

oh...
Hopefully this tool will make implementation a bit more of a priority ......

**Comment by alfonsogarciacaro** [comment]
I think I saw that error once though I don't remember well. I will try to check. Is the Analyzers SDK used only to update the UI on the fly? Can the UI be updated when the file is saved? That's what Fable does.

**Comment by SilkyFowl** [comment]
@alfonsogarciacaro 
>  I will try to check.

Thank you very much.

> Can the UI be updated when the file is saved?

I can't do it at the moment, but I think it could be achieved by using FileSystemWatcher or by monitoring file update times. I hope to achieve this at some point.

**Comment by SilkyFowl** [comment]
image

I thought a case label with no value could be avoided, but perhaps it is even more troublesome...

**Comment by SilkyFowl** [comment]
Since this bug is related to code analysis, it should not be a problem if the DU is precompiled. In other words, if I don't write the DU in the code I want to Preview, I should be able to work around it.
I would like to add test code and sample code to verify this.

**Comment by dsyme** [comment]
What specific construct is being used that is triggering that error?

**Comment by SilkyFowl** [comment]
@dsyme Thanks for your comments, I see great potential in Analyzer.SDK and the draft of Modernizing F# Analysis (dotnet/fsharp#11057) that would follow in its footsteps.

We have not fully verified this yet, so this is current result.
I was looking into it, and I got an unintended exception when I wrote a DU containing a label case with no value, except at the end of the code.


Work

```fsharp

// Some code...

type AnyDuHasNoValueLabelCase =
    | Foo
    | Bar of int

```

Not Work

```fsharp

// Some code...
// So far, I can analyze it correctly.

type AnyDuHasNoValueLabelCase =
    | Foo
    | Bar of int

// Other some code...
// Not work


```

Test Code is here.

https://github.com/SilkyFowl/Avalonia.FuncUI.LiveView/blob/f991cb3c8e17b198b2ab77471cbb63f0e995434d/tests/Avalonia.FuncUI.LiveView.Core.Tests/FuncUIAnalysisTests.fs#L231-L360

**Comment by SilkyFowl** [comment]
If it''s considered v0.0.1, it looks good?

https://user-images.githubusercontent.com/16532218/173259466-9b584387-536c-4445-8433-f4624a4cc5f5.mp4

**Comment by SilkyFowl** [comment]
How to use(memo)

```diff
{
    "FSharp.enableAnalyzers": true,
    "FSharp.analyzersPath": [
-        "packages/Analyzers",
+        "packages/analyzers",
        "analyzers"
    ]
}
```

```
source https://api.nuget.org/v3/index.json

storage: symlink
framework: net6.0
nuget Avalonia.Desktop >= 0.10.12
nuget Avalonia.Diagnostics >= 0.10.12
nuget FSharp.Core content: none
nuget JaggerJo.Avalonia.FuncUI >= 0.5.0
nuget JaggerJo.Avalonia.FuncUI.DSL >= 0.5.0
nuget JaggerJo.Avalonia.FuncUI.Elmish >= 0.5.0
nuget Avalonia.Angle.Windows.Natives <= 2.1.0.2020091801
nuget SilkyFowl.Avalonia.FuncUI.LiveView

// [ Analyzers Group ]
group Analyzers
    framework: net6.0
    source https://api.nuget.org/v3/index.json
    nuget SilkyFowl.Avalonia.FuncUI.LiveView.Analyzer

```

```diff
--- a/./src/LivePreviewApp/Counter.fs
+++ b/./src/LivePreviewApp/Counter.fs
@@ -1,14 +1,18 @@
-namespace LivePreviewApp
+namespace LivePreviewApp
 
 module Counter =
     open Avalonia.Controls
     open Avalonia.FuncUI
     open Avalonia.FuncUI.DSL
+    open Avalonia.FuncUI.LiveView.Core.Types
     open Avalonia.Layout
 
-    let view =
-        Component(fun ctx ->
-            let state = ctx.useState 0
+    let counter name num =
+        Component.create(
+            name,
+            fun ctx ->
+            let state = ctx.usePassed num
+
             DockPanel.create [
                 DockPanel.verticalAlignment VerticalAlignment.Center
                 DockPanel.horizontalAlignment HorizontalAlignment.Center
@@ -46,3 +50,16 @@ module Counter =
                 ]
             ]
         )
+
+    [<LivePreview>]
+    let preview()=
+        let state = new State<_> 0
+        counter "counter" state
+
+    let view =
+        Component(fun ctx ->
+            let state = ctx.useState 0
+            counter "counter" state
+        )
+
+    
```

**Comment by SilkyFowl** [comment]
@alfonsogarciacaro @dsyme 
DU issues are inconvenient but there is a workaround, so I'm going to merge it for now.
I will follow up with a new issue in the future.

**Pull request merged**
